"""Step 5 - generate Top-K recommendations and qualitative examples.

Writes a human-readable report (outputs/recommendations/sample_recommendations.md)
and a JSON dump: sample users with their liked history + Top-10 recommendations
(hits against held-out relevant items marked), success/failure cases, item-item
"more like this" lists, and Item-CF explanations.
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src"))

import numpy as np
import config
import data_processing as dp
import recommend as rc
from models import SVDModel, ItemCFModel, PopularityModel, PopBlendModel

K = config.TOP_K
THR = config.RELEVANCE_THRESHOLD


def fmt_recs(recs):
    lines = []
    for n, r in enumerate(recs, 1):
        mark = "  <-- HIT (in held-out likes)" if r["hit"] else ""
        lines.append(f"  {n:2d}. {r['title']}  (score {r['score']}){mark}")
    return "\n".join(lines)


def main():
    ds = dp.Dataset.load(os.path.join(config.PROCESSED_DIR, "dataset.npz"))
    titles = dp.load_movie_titles()
    idx = rc.build_user_index(ds)

    svd = SVDModel().load(os.path.join(config.MODEL_DIR, "svd.npz"))
    icf = ItemCFModel().load(os.path.join(config.MODEL_DIR, "itemcf.npz"))
    icf.attach_profiles(ds.train_u, ds.train_i, ds.train_r, ds.n_users)
    hybrid = PopBlendModel(svd, ds.item_popularity, alpha=1.0)

    # eligible users: enough history + held-out likes
    n_train = np.array([len(x) for x in idx["train_i"]])
    n_rel = np.array([int((idx["test_r"][u] >= THR).sum()) for u in range(ds.n_users)])
    eligible = np.where((n_train >= 20) & (n_rel >= 5))[0]
    rng = np.random.default_rng(7)
    sample_users = rng.choice(eligible, size=min(4, len(eligible)), replace=False)

    report = ["# Sample Recommendations & Qualitative Analysis\n",
              f"Top-{K} generated by scoring all {ds.n_items} movies, removing movies "
              f"already rated in train, and taking the highest-scoring items. "
              f'A "HIT" means the movie is in the user\'s held-out test set with rating '
              f">= {THR}.\n"]
    dump = {"sample_users": [], "more_like_this": [], "success": None, "failure": None}

    for u in sample_users:
        liked = rc.liked_history(ds, u, titles, idx, n=6)
        icf_recs = rc.recommend(icf, u, ds, titles, idx, k=K, relevance_threshold=THR)
        svd_recs = rc.recommend(svd, u, ds, titles, idx, k=K, relevance_threshold=THR)
        report.append(f"\n## User #{int(u)}  ({int(n_train[u])} train ratings, "
                      f"{int(n_rel[u])} held-out likes)")
        report.append("\n**Likes (top rated in history):**")
        report.append("\n".join(f"  - {t}  ({r:.0f}*)" for t, r in liked))
        report.append(f"\n**Item-CF Top-{K}**  (hits: "
                      f"{sum(r['hit'] for r in icf_recs)}/{K}):")
        report.append(fmt_recs(icf_recs))
        report.append(f"\n**SVD Top-{K}**  (hits: {sum(r['hit'] for r in svd_recs)}/{K}):")
        report.append(fmt_recs(svd_recs))
        # explanation for the first Item-CF hit (or first rec)
        target = next((r for r in icf_recs if r["hit"]), icf_recs[0])
        why = rc.explain_itemcf(icf, u, target["item_idx"], ds, titles, idx, n=3)
        if why:
            report.append(f"\n*Why Item-CF recommended '{target['title']}': because you "
                          f"rated " + ", ".join(f"{t} (sim {s})" for t, s in why) + ".*")
        dump["sample_users"].append({
            "user": int(u), "likes": liked,
            "itemcf_top10": icf_recs, "svd_top10": svd_recs})

    # explicit success & failure cases (Item-CF)
    hits_per_user = []
    for u in eligible[:4000]:
        recs = rc.recommend(icf, u, ds, titles, idx, k=K, relevance_threshold=THR)
        hits_per_user.append((int(u), sum(r["hit"] for r in recs)))
    hits_per_user.sort(key=lambda x: x[1])
    fail_u = hits_per_user[0][0]
    succ_u = hits_per_user[-1][0]
    for tag, uu in [("success", succ_u), ("failure", fail_u)]:
        recs = rc.recommend(icf, uu, ds, titles, idx, k=K, relevance_threshold=THR)
        liked = rc.liked_history(ds, uu, titles, idx, n=5)
        dump[tag] = {"user": uu, "hits": sum(r["hit"] for r in recs),
                     "likes": liked, "top10": recs}
        report.append(f"\n## {tag.title()} case - User #{uu}  "
                      f"(Item-CF hits: {sum(r['hit'] for r in recs)}/{K})")
        report.append("**Likes:** " + "; ".join(t for t, _ in liked))
        report.append(fmt_recs(recs))

    # "more like this" for the most popular recognisable movies
    report.append("\n## 'More like this' (Item-CF item-item similarity)")
    top_pop = np.argsort(ds.item_popularity)[::-1][:6]
    for it in top_pop:
        sims = rc.similar_movies(icf, int(it), ds, titles, n=6)
        report.append(f"\n**{rc.title_of(ds, titles, it)}** ->")
        report.append("\n".join(f"  - {t}  (sim {s})" for t, s in sims))
        dump["more_like_this"].append({"movie": rc.title_of(ds, titles, it),
                                       "similar": sims})

    os.makedirs(config.REC_DIR, exist_ok=True)
    with open(os.path.join(config.REC_DIR, "sample_recommendations.md"), "w") as fh:
        fh.write("\n".join(report) + "\n")
    with open(os.path.join(config.REC_DIR, "sample_recommendations.json"), "w") as fh:
        json.dump(dump, fh, indent=2)
    print("\n".join(report))
    print(f"\nSaved -> {config.REC_DIR}/sample_recommendations.md , .json")


if __name__ == "__main__":
    main()
